<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { getCurrentWindow } from '@tauri-apps/api/window'
import type { PetState } from '../types'
import { chooseIdleActivity, type PetIdleActivity } from '../services/petLife'
import { buildPetMood, moodLabel, type PetMood } from '../services/petMood'
import { characterLabels, defaultPetSettings, loadPetSettings, motionMultiplier, personalityLabels, personalityMotionMultiplier, personalitySleepMultiplier, petCharacters, savePetSettings, type PetSettings } from '../services/petSettings'

const props=withDefaults(defineProps<{state:PetState;draggable?:boolean;pointerDirection?:'left'|'right';choreographyAction?:string}>(),{draggable:true,pointerDirection:'right',choreographyAction:''})
const emit=defineEmits<{(e:'pet'):void;(e:'menu'):void}>()
const eyeX=ref(0),eyeY=ref(0),isPetting=ref(false),idleActivity=ref<PetIdleActivity>('rest'),mood=ref<PetMood>('calm'),energy=ref(78),affection=ref(45),roamX=ref(0),roamY=ref(0),lastInteractionAt=ref(Date.now()),recentPets=ref(0),settingsOpen=ref(false)
const settings=ref<PetSettings>(loadPetSettings()),draft=ref<PetSettings>({...settings.value})
const mochi=ref(false),hunting=ref(false),kneading=ref(false),overheat=ref(false),scrolling=ref(false),reminderBubble=ref(''),purr=ref(false)
let cycleIndex=0,lifeTimer:number|undefined,reminderTimer:number|undefined,huntTimer:number|undefined,kneadTimer:number|undefined,overheatTimer:number|undefined,scrollTimer:number|undefined,purrTimer:number|undefined
let lastPointer={x:0,y:0,t:performance.now()},keyHits:number[]=[]
let lastStretchAt=Date.now(),lastWaterAt=Date.now()

const autonomous=computed(()=>props.state==='idle'||props.state==='sleeping'),showThought=computed(()=>props.state==='thinking'||props.choreographyAction==='think'),showSparkles=computed(()=>props.state==='success'||props.choreographyAction==='celebrate')
const petStyle=computed(()=>autonomous.value&&settings.value.autonomousMovement?{transform:`translate(${roamX.value}px, ${roamY.value}px)`}:undefined)
const lifeTitle=computed(()=>`${settings.value.name} · ${characterLabels[settings.value.character]} · ${personalityLabels[settings.value.personality]} · Mood: ${moodLabel(mood.value)} · Energy ${energy.value}% · Affection ${affection.value}%`)
const sleepAfterMs=computed(()=>settings.value.sleepAfterMinutes*60000*personalitySleepMultiplier(settings.value.personality))
const ownerPrefix=computed(()=>settings.value.ownerName?`${settings.value.ownerName}, `:'')

function registerInteraction(){lastInteractionAt.value=Date.now();if(props.state==='sleeping')idleActivity.value='rest'}
function trackEyes(e:MouseEvent){registerInteraction();const r=(e.currentTarget as HTMLElement).getBoundingClientRect(),x=(e.clientX-(r.left+r.width/2))/r.width,y=(e.clientY-(r.top+r.height/2))/r.height;eyeX.value=Math.max(-3,Math.min(3,x*8));eyeY.value=Math.max(-2,Math.min(2,y*6))}
function resetEyes(){eyeX.value=0;eyeY.value=0}
async function startDrag(e:MouseEvent){registerInteraction();if(!props.draggable||e.button!==0)return;mochi.value=true;window.setTimeout(()=>mochi.value=false,700);try{await getCurrentWindow().startDragging()}catch{}}
function pet(e:MouseEvent){registerInteraction();recentPets.value=Math.min(8,recentPets.value+1);isPetting.value=true;const r=(e.currentTarget as HTMLElement).getBoundingClientRect(),onHead=e.clientY-r.top<105;purr.value=onHead;emit('pet');window.setTimeout(()=>isPetting.value=false,700);if(purrTimer)clearTimeout(purrTimer);purrTimer=window.setTimeout(()=>purr.value=false,1300)}
function openSettings(e:MouseEvent){e.preventDefault();if(!props.draggable)return;draft.value={...settings.value};settingsOpen.value=true}
function applySettings(){settings.value=savePetSettings(draft.value);settingsOpen.value=false;registerInteraction();lastStretchAt=lastWaterAt=Date.now();updateLife()}
function externalSettings(e:Event){const d=(e as CustomEvent<PetSettings>).detail;if(d)settings.value={...d}}

function updateLife(){if(!autonomous.value){idleActivity.value='rest';roamX.value=roamY.value=0;return}const inactiveMs=Date.now()-lastInteractionAt.value,life=chooseIdleActivity(inactiveMs,cycleIndex,sleepAfterMs.value),snap=buildPetMood({inactiveMs,recentPets:recentPets.value,cycleIndex});idleActivity.value=life.activity;mood.value=settings.value.personality==='playful'&&recentPets.value>0?'playful':settings.value.personality==='sleepy'&&inactiveMs>45000?'sleepy':snap.mood;energy.value=snap.energy;affection.value=snap.affection;const movement=motionMultiplier(settings.value.motionLevel)*personalityMotionMultiplier(settings.value.personality);roamX.value=!settings.value.autonomousMovement||life.asleep?0:Math.round(snap.roamX*movement);roamY.value=life.asleep?3:!settings.value.autonomousMovement?0:Math.round(snap.roamY*movement);cycleIndex++;if(cycleIndex%3===0&&recentPets.value>0)recentPets.value--}
function globalMouseMove(e:MouseEvent){if(!settings.value.cursorHunting||!autonomous.value)return;const now=performance.now(),dt=Math.max(8,now-lastPointer.t),dx=e.clientX-lastPointer.x,dy=e.clientY-lastPointer.y,speed=Math.hypot(dx,dy)/dt*1000;lastPointer={x:e.clientX,y:e.clientY,t:now};if(speed>950){hunting.value=true;registerInteraction();if(huntTimer)clearTimeout(huntTimer);huntTimer=window.setTimeout(()=>hunting.value=false,950)}}
function keyDown(){if(!settings.value.keyboardReactions||!autonomous.value)return;const now=Date.now();keyHits=keyHits.filter(t=>now-t<1800);keyHits.push(now);kneading.value=true;if(kneadTimer)clearTimeout(kneadTimer);kneadTimer=window.setTimeout(()=>kneading.value=false,220);if(keyHits.length>=13){overheat.value=true;if(overheatTimer)clearTimeout(overheatTimer);overheatTimer=window.setTimeout(()=>{overheat.value=false;keyHits=[]},2400)}}
function wheel(){if(!settings.value.scrollReactions||!autonomous.value)return;scrolling.value=true;if(scrollTimer)clearTimeout(scrollTimer);scrollTimer=window.setTimeout(()=>scrolling.value=false,900)}
function showReminder(message:string){reminderBubble.value=message;window.setTimeout(()=>{if(reminderBubble.value===message)reminderBubble.value=''},7000)}
function checkWellness(){const now=Date.now(),stretch=settings.value.stretchReminderMinutes*60000,water=settings.value.waterReminderMinutes*60000;if(stretch>0&&now-lastStretchAt>=stretch){lastStretchAt=now;showReminder(`${ownerPrefix.value}time to stretch with me! 🐾`);idleActivity.value='stretch'}else if(water>0&&now-lastWaterAt>=water){lastWaterAt=now;showReminder(`${ownerPrefix.value}please drink some water 💧`)}}

onMounted(()=>{updateLife();lifeTimer=window.setInterval(updateLife,12000);reminderTimer=window.setInterval(checkWellness,15000);window.addEventListener('nyanmate-pet-settings-changed',externalSettings);window.addEventListener('mousemove',globalMouseMove);window.addEventListener('keydown',keyDown);window.addEventListener('wheel',wheel,{passive:true})})
onUnmounted(()=>{if(lifeTimer)clearInterval(lifeTimer);if(reminderTimer)clearInterval(reminderTimer);window.removeEventListener('nyanmate-pet-settings-changed',externalSettings);window.removeEventListener('mousemove',globalMouseMove);window.removeEventListener('keydown',keyDown);window.removeEventListener('wheel',wheel)})
</script>

<template><div class="pet-customization-shell" :class="{'peek-shell':settings.peekingMode}">
<div v-if="settings.fixedMessage&&draggable" class="pet-fixed-message">📌 {{settings.fixedMessage}}</div><div v-if="reminderBubble" class="pet-reminder-bubble">{{reminderBubble}}</div>
<div class="nyan-pet" :class="[`state-${state}`,`activity-${idleActivity}`,`mood-${mood}`,`personality-${settings.personality}`,`accessory-${settings.accessory}`,`character-${settings.character}`,`pointer-${pointerDirection}`,choreographyAction?`pet-choreo-${choreographyAction}`:'',{petting:isPetting,'drag-disabled':!draggable,'mochi-drag':mochi,'cursor-hunting':hunting,'keyboard-kneading':kneading,'overheat-mode':overheat,'scroll-reaction':scrolling,'peek-mode':settings.peekingMode}]" :style="petStyle" @mousemove="trackEyes" @mouseleave="resetEyes" @mousedown="startDrag" @click.stop="pet" @dblclick.stop="emit('menu')" @contextmenu="openSettings" :title="lifeTitle">
<div v-if="scrolling" class="tissue-roll"><i></i></div><div v-if="overheat" class="heat-steam"><i></i><i></i><i></i></div><div v-if="purr" class="purr-bubble">prrrr ♡</div><div v-if="hunting" class="hunt-mark">⌖</div>
<div class="tail"><span class="tail-tip"></span><span class="tail-stripes"></span></div><div class="body"><div class="back-patch"></div><div class="belly"></div><div class="body-markings"></div><div class="paw paw-left"></div><div class="paw paw-right"></div><div v-if="settings.accessory==='scarf'" class="scarf-knot"></div><div v-if="settings.accessory==='scarf'" class="scarf-tail"></div></div>
<div class="head"><div class="ear ear-left"><span></span></div><div class="ear ear-right"><span></span></div><div class="gray-cap"></div><div class="face-patch patch-left"></div><div class="face-patch patch-right"></div><div class="forehead-markings"></div><div class="muzzle-marking"></div><div class="eye eye-left"><i :style="{transform:`translate(${eyeX}px,${eyeY}px)`}"></i><b></b></div><div class="eye eye-right"><i :style="{transform:`translate(${eyeX}px,${eyeY}px)`}"></i><b></b></div><div class="cheek cheek-left"></div><div class="cheek cheek-right"></div><div class="nose"></div><div class="mouth"></div><div class="whiskers whiskers-left"></div><div class="whiskers whiskers-right"></div><template v-if="settings.accessory==='scarf'"><div class="scarf-band"></div><div class="scarf-badge">✦</div></template><div v-if="settings.accessory==='bell'" class="pet-bell">●</div><div v-if="settings.accessory==='bow'" class="pet-bow">◆</div><div v-if="showThought" class="thought">•••</div><div v-if="state==='coding'" class="headphones"><span></span></div><div v-if="state==='coding'" class="laptop"><span>⌘</span></div><template v-if="state==='teaching'"><div class="teacher-glasses"><span></span><span></span></div><div class="graduation-cap"><i></i></div><div class="teaching-pointer"></div></template><div v-if="showSparkles" class="sparkles">✦ ✧</div><div v-if="state==='error'" class="alert">!</div><div v-if="state==='sleeping'||idleActivity==='doze'" class="sleep-z">Z z</div><div v-if="mood==='playful'&&autonomous" class="mood-heart">♥</div><div v-if="mood==='curious'&&autonomous" class="mood-mark">?</div></div><div v-if="draggable" class="pet-name-tag">{{settings.name}}</div></div>
<div v-if="settingsOpen" class="pet-settings-popover pet-settings-v28" @click.stop @mousedown.stop><div class="pet-settings-head"><strong>🐾 Cat Collection & Reactions</strong><button @click="settingsOpen=false">×</button></div><label>Cat name<input v-model="draft.name" maxlength="24"/></label><label>Your name<input v-model="draft.ownerName" maxlength="32" placeholder="Used in reminders"/></label><label>Character<select v-model="draft.character"><option v-for="cat in petCharacters" :key="cat" :value="cat">{{characterLabels[cat]}}</option></select></label><div class="cat-preview-grid"><button v-for="cat in petCharacters" :key="cat" :class="['cat-swatch',`swatch-${cat}`,{active:draft.character===cat}]" @click="draft.character=cat"><i></i><span>{{characterLabels[cat].split(' · ')[0]}}</span></button></div><label>Personality<select v-model="draft.personality"><option value="gentle">Gentle</option><option value="playful">Playful</option><option value="focused">Focused</option><option value="sleepy">Sleepy</option></select></label><label>Accessory<select v-model="draft.accessory"><option value="scarf">Signature scarf</option><option value="bell">Bell</option><option value="bow">Bow</option><option value="none">None</option></select></label><label>Fixed message<input v-model="draft.fixedMessage" maxlength="120" placeholder="Pinned above the cat"/></label><div class="pet-reminder-grid"><label>Stretch every<input v-model.number="draft.stretchReminderMinutes" type="number" min="0" max="720"/><small>minutes · 0 = off</small></label><label>Water every<input v-model.number="draft.waterReminderMinutes" type="number" min="0" max="720"/><small>minutes · 0 = off</small></label></div><label>Motion<select v-model="draft.motionLevel"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label><label>Sleep after <span>{{draft.sleepAfterMinutes}} min</span><input v-model.number="draft.sleepAfterMinutes" type="range" min="1" max="30"/></label><div class="reaction-toggles"><label><input v-model="draft.autonomousMovement" type="checkbox"/> Autonomous movement</label><label><input v-model="draft.cursorHunting" type="checkbox"/> Hunt fast cursor</label><label><input v-model="draft.keyboardReactions" type="checkbox"/> Keyboard kneading + overheat</label><label><input v-model="draft.scrollReactions" type="checkbox"/> Scroll tissue reaction</label><label><input v-model="draft.peekingMode" type="checkbox"/> Peeking mode</label></div><div class="pet-settings-actions"><button @click="draft={...defaultPetSettings}">Defaults</button><button class="primary" @click="applySettings">Save</button></div><small>Keyboard, cursor, and scroll reactions currently observe activity inside the NyanMate WebView. Native system-wide hooks are a separate future integration.</small></div></div></template>
