<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { getCurrentWindow } from '@tauri-apps/api/window'
import type { PetState } from '../types'
import { chooseIdleActivity, type PetIdleActivity } from '../services/petLife'
import { buildPetMood, moodLabel, type PetMood } from '../services/petMood'
import { characterLabels, defaultPetSettings, loadPetSettings, motionMultiplier, personalityLabels, personalityMotionMultiplier, personalitySleepMultiplier, petCharacters, savePetSettings, type PetSettings } from '../services/petSettings'
const props=withDefaults(defineProps<{state:PetState;draggable?:boolean;pointerDirection?:'left'|'right';choreographyAction?:string}>(),{draggable:true,pointerDirection:'right',choreographyAction:''})
const emit=defineEmits<{(e:'pet'):void;(e:'menu'):void}>()
const eyeX=ref(0),eyeY=ref(0),isPetting=ref(false),idleActivity=ref<PetIdleActivity>('rest'),mood=ref<PetMood>('calm'),energy=ref(78),affection=ref(45),roamX=ref(0),roamY=ref(0),lastInteractionAt=ref(Date.now()),recentPets=ref(0),settingsOpen=ref(false)
const settings=ref<PetSettings>(loadPetSettings()),draft=ref<PetSettings>({...settings.value});let cycleIndex=0,lifeTimer:number|undefined
const autonomous=computed(()=>props.state==='idle'||props.state==='sleeping'),showThought=computed(()=>props.state==='thinking'||props.choreographyAction==='think'),showSparkles=computed(()=>props.state==='success'||props.choreographyAction==='celebrate')
const petStyle=computed(()=>autonomous.value&&settings.value.autonomousMovement?{transform:`translate(${roamX.value}px, ${roamY.value}px)`}:undefined)
const lifeTitle=computed(()=>`${settings.value.name} · ${characterLabels[settings.value.character]} · ${personalityLabels[settings.value.personality]} · Mood: ${moodLabel(mood.value)} · Energy ${energy.value}% · Affection ${affection.value}%`)
const sleepAfterMs=computed(()=>settings.value.sleepAfterMinutes*60000*personalitySleepMultiplier(settings.value.personality))
function registerInteraction(){lastInteractionAt.value=Date.now();if(props.state==='sleeping')idleActivity.value='rest'}
function trackEyes(e:MouseEvent){registerInteraction();const r=(e.currentTarget as HTMLElement).getBoundingClientRect(),x=(e.clientX-(r.left+r.width/2))/r.width,y=(e.clientY-(r.top+r.height/2))/r.height;eyeX.value=Math.max(-3,Math.min(3,x*8));eyeY.value=Math.max(-2,Math.min(2,y*6))}
function resetEyes(){eyeX.value=0;eyeY.value=0} async function startDrag(e:MouseEvent){registerInteraction();if(!props.draggable||e.button!==0)return;try{await getCurrentWindow().startDragging()}catch{}}
function pet(){registerInteraction();recentPets.value=Math.min(8,recentPets.value+1);isPetting.value=true;emit('pet');setTimeout(()=>isPetting.value=false,700)}
function openSettings(e:MouseEvent){e.preventDefault();if(!props.draggable)return;draft.value={...settings.value};settingsOpen.value=true} function applySettings(){settings.value=savePetSettings(draft.value);settingsOpen.value=false;registerInteraction();updateLife()} function externalSettings(e:Event){const d=(e as CustomEvent<PetSettings>).detail;if(d)settings.value={...d}}
function updateLife(){if(!autonomous.value){idleActivity.value='rest';roamX.value=roamY.value=0;return}const inactiveMs=Date.now()-lastInteractionAt.value,life=chooseIdleActivity(inactiveMs,cycleIndex,sleepAfterMs.value),snap=buildPetMood({inactiveMs,recentPets:recentPets.value,cycleIndex});idleActivity.value=life.activity;mood.value=settings.value.personality==='playful'&&recentPets.value>0?'playful':settings.value.personality==='sleepy'&&inactiveMs>45000?'sleepy':snap.mood;energy.value=snap.energy;affection.value=snap.affection;const movement=motionMultiplier(settings.value.motionLevel)*personalityMotionMultiplier(settings.value.personality);roamX.value=!settings.value.autonomousMovement||life.asleep?0:Math.round(snap.roamX*movement);roamY.value=life.asleep?3:!settings.value.autonomousMovement?0:Math.round(snap.roamY*movement);cycleIndex++;if(cycleIndex%3===0&&recentPets.value>0)recentPets.value--}
onMounted(()=>{updateLife();lifeTimer=setInterval(updateLife,12000);window.addEventListener('nyanmate-pet-settings-changed',externalSettings)});onUnmounted(()=>{if(lifeTimer)clearInterval(lifeTimer);window.removeEventListener('nyanmate-pet-settings-changed',externalSettings)})
</script>
<template><div class="pet-customization-shell"><div class="nyan-pet" :class="[`state-${state}`,`activity-${idleActivity}`,`mood-${mood}`,`personality-${settings.personality}`,`accessory-${settings.accessory}`,`character-${settings.character}`,`pointer-${pointerDirection}`,choreographyAction?`pet-choreo-${choreographyAction}`:'',{petting:isPetting,'drag-disabled':!draggable}]" :style="petStyle" @mousemove="trackEyes" @mouseleave="resetEyes" @mousedown="startDrag" @click.stop="pet" @dblclick.stop="emit('menu')" @contextmenu="openSettings" :title="lifeTitle">
<div class="tail"><span class="tail-tip"></span></div><div class="body"><div class="back-patch"></div><div class="belly"></div><div class="paw paw-left"></div><div class="paw paw-right"></div><div v-if="settings.accessory==='scarf'" class="scarf-knot"></div><div v-if="settings.accessory==='scarf'" class="scarf-tail"></div></div>
<div class="head"><div class="ear ear-left"><span></span></div><div class="ear ear-right"><span></span></div><div class="gray-cap"></div><div class="face-patch patch-left"></div><div class="face-patch patch-right"></div><div class="eye eye-left"><i :style="{transform:`translate(${eyeX}px,${eyeY}px)`}"></i><b></b></div><div class="eye eye-right"><i :style="{transform:`translate(${eyeX}px,${eyeY}px)`}"></i><b></b></div><div class="cheek cheek-left"></div><div class="cheek cheek-right"></div><div class="nose"></div><div class="mouth"></div><div class="whiskers whiskers-left"></div><div class="whiskers whiskers-right"></div><template v-if="settings.accessory==='scarf'"><div class="scarf-band"></div><div class="scarf-badge">✦</div></template><div v-if="settings.accessory==='bell'" class="pet-bell">●</div><div v-if="settings.accessory==='bow'" class="pet-bow">◆</div><div v-if="showThought" class="thought">•••</div><div v-if="state==='coding'" class="headphones"><span></span></div><div v-if="state==='coding'" class="laptop"><span>⌘</span></div><template v-if="state==='teaching'"><div class="teacher-glasses"><span></span><span></span></div><div class="graduation-cap"><i></i></div><div class="teaching-pointer"></div></template><div v-if="showSparkles" class="sparkles">✦ ✧</div><div v-if="state==='error'" class="alert">!</div><div v-if="state==='sleeping'||idleActivity==='doze'" class="sleep-z">Z z</div><div v-if="mood==='playful'&&autonomous" class="mood-heart">♥</div><div v-if="mood==='curious'&&autonomous" class="mood-mark">?</div></div><div v-if="draggable" class="pet-name-tag">{{settings.name}}</div></div>
<div v-if="settingsOpen" class="pet-settings-popover" @click.stop @mousedown.stop><div class="pet-settings-head"><strong>🐾 Cat Collection</strong><button @click="settingsOpen=false">×</button></div><label>Name<input v-model="draft.name" maxlength="24"/></label><label>Character<select v-model="draft.character"><option v-for="cat in petCharacters" :key="cat" :value="cat">{{characterLabels[cat]}}</option></select></label><div class="cat-preview-grid"><button v-for="cat in petCharacters" :key="cat" :class="['cat-swatch',`swatch-${cat}`,{active:draft.character===cat}]" @click="draft.character=cat"><i></i><span>{{characterLabels[cat].split(' · ')[0]}}</span></button></div><label>Personality<select v-model="draft.personality"><option value="gentle">Gentle</option><option value="playful">Playful</option><option value="focused">Focused</option><option value="sleepy">Sleepy</option></select></label><label>Accessory<select v-model="draft.accessory"><option value="scarf">Signature scarf</option><option value="bell">Bell</option><option value="bow">Bow</option><option value="none">None</option></select></label><label>Motion<select v-model="draft.motionLevel"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label><label>Sleep after <span>{{draft.sleepAfterMinutes}} min</span><input v-model.number="draft.sleepAfterMinutes" type="range" min="1" max="30"/></label><label class="pet-settings-check"><input v-model="draft.autonomousMovement" type="checkbox"/> Autonomous movement</label><div class="pet-settings-actions"><button @click="draft={...defaultPetSettings}">Defaults</button><button class="primary" @click="applySettings">Save</button></div><small>8 original NyanMate cat variants. Settings stay local on this device.</small></div></div></template>
