import { createApp } from 'vue'
import { getCurrentWindow } from '@tauri-apps/api/window'
import App from './App.vue'
import PresenterView from './components/PresenterView.vue'
import ClassReportDashboard from './components/ClassReportDashboard.vue'
import SmartAgendaDashboard from './components/SmartAgendaDashboard.vue'
import FileAssistantDashboard from './components/FileAssistantDashboard.vue'
import './style.css'
import './presentation.css'
import './v05.css'
import './v06.css'
import './v07.css'
import './v08.css'
import './v09.css'
import './v10.css'
import './v11.css'
import './v12.css'
import './v13.css'
import './v14.css'
import './v15.css'
import './v16.css'
import './v17.css'
import './v18.css'
import './v19.css'
import './v20.css'
import './v21.css'
import './v22.css'
import './v23.css'
import './v24.css'
import './v25.css'
import './v26.css'
import './v27.css'
const label=getCurrentWindow().label
const Root=label==='presenter'?PresenterView:label==='reports'?ClassReportDashboard:label==='agenda'?SmartAgendaDashboard:label==='assistant'?FileAssistantDashboard:App
createApp(Root).mount('#app')
